ALTER TABLE "character_skills" ALTER COLUMN "flat_modifier" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "character_skills" ALTER COLUMN "flat_modifier" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "character_skills" ALTER COLUMN "bonus_dice" SET DEFAULT '1d4';--> statement-breakpoint
ALTER TABLE "character_skills" ALTER COLUMN "bonus_dice" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "equipment" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "equipment" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "ability" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "utility" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "utility" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "phy" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "phy" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "vit" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "vit" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "sen" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "sen" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "wil" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "wil" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "acu" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "acu" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "pre" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "stats" ALTER COLUMN "pre" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "traits" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "traits" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "wounds" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "wounds" ALTER COLUMN "tier" SET DEFAULT 'Trivial';--> statement-breakpoint
ALTER TABLE "wounds" ALTER COLUMN "tier" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "wounds" ALTER COLUMN "severity" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "wounds" ALTER COLUMN "severity" SET NOT NULL;